version: '2'

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=exercise
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
    ports:
      - 8082:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-editor

